name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /var/www/tarot_diary
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # 設定 ~/.supervisorctl.conf 並寫入 Secrets 帳密
            cat > ~/.supervisorctl.conf <<CONF
[supervisorctl]
serverurl=http://127.0.0.1:9001
username=${{ secrets.EC2_SUPERVISOR_USER }}
password=${{ secrets.EC2_SUPERVISOR_PASS }}
CONF

            # 重啟 Laravel queue worker
            supervisorctl reread
            supervisorctl update
            supervisorctl restart laravel-worker:*
          EOF
